apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ok
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ok
  template:
    metadata:
      labels:
        app: app-ok
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-ok
  namespace: apps
spec:
  selector:
    app: app-ok
  type: NodePort          # <--- adiciona NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31001      # porta que o outro cluster vai acessar