apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info

    [INPUT]
        Name  tail
        Path  /var/log/pods/**/*.log
        Tag   kube.*
        Mem_Buf_Limit 10MB
        Skip_Long_Lines On

    [FILTER]
        Name   kubernetes
        Match  kube.*
        Merge_Log On
        Keep_Log Off

    [FILTER]
        Name    grep
        Match   kube.*
        Regex   $kubernetes['namespace_name'] ^apps$

    [OUTPUT]
        Name  loki
        Match *
        Host  host.docker.internal
        Port  30001
        URI   /loki/api/v1/push

    [OUTPUT]
        Name  es
        Match *
        Host  host.docker.internal
        Port  30002
        Index apps-logs
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: fluentbit
          image: fluent/fluent-bit:2.2.0
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc
            - name: varlog
              mountPath: /var/log/pods
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: fluentbit-config
        - name: varlog
          hostPath:
            path: /var/log/pods
            type: Directory
