apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-error
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-error
  template:
    metadata:
      labels:
        app: app-error
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:1.0
          args:
            - "-listen=:5678"
            - "-text=error-simulator"
          ports:
            - containerPort: 5678
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-error
  namespace: apps
spec:
  selector:
    app: app-err
  type: NodePort          # <--- adiciona NodePort
  ports:
    - port: 80
      targetPort: 5678
      nodePort: 31002      # porta que o outro cluster vai acessar